#!/usr/bin/env python3

import sys
from pathlib import Path

SCRIPTS_PATH = Path(__file__).parent
ROOT_PATH = SCRIPTS_PATH.parent
SKILLS_PATH = ROOT_PATH / "skills"
TEMPLATE_PATH = ROOT_PATH / "template" / "SKILL.md"


def load_template() -> str:
    if TEMPLATE_PATH.exists():
        return TEMPLATE_PATH.read_text()
    raise FileNotFoundError(f"Template not found: {TEMPLATE_PATH}")


SKILLS = {
    "ai-ml": [
        ("airflow", "Apache Airflow workflow orchestration. Use for data pipelines."),
        ("catboost", "CatBoost gradient boosting with categoricals. Use for tabular ML."),
        ("claude", "Anthropic Claude AI models for analysis and coding. Use for AI assistants."),
        ("comfyui", "ComfyUI node-based Stable Diffusion. Use for image generation."),
        ("cursor-ai", "Cursor AI editor with context-aware coding. Use for AI-assisted development."),
        ("dalle", "DALL-E OpenAI image generation. Use for image creation."),
        ("dask", "Dask parallel computing library. Use for scaling pandas."),
        ("dbt", "dbt data transformation with SQL. Use for data pipelines."),
        ("deepseek", "DeepSeek AI models for coding. Use for code AI."),
        ("fastai", "fast.ai deep learning library. Use for practical deep learning."),
        ("gemini", "Google Gemini AI models for multimodal tasks. Use for multimodal AI."),
        ("github-copilot", "GitHub Copilot AI code suggestions and chat. Use for code completion."),
        ("huggingface", "Hugging Face transformers library and hub. Use for NLP models."),
        ("jax", "JAX high-performance numerical computing. Use for ML research."),
        ("jupyter", "Jupyter notebooks for interactive computing. Use for data exploration."),
        ("keras", "Keras high-level neural network API. Use for deep learning."),
        ("langchain", "LangChain LLM application framework with chains and agents. Use for LLM orchestration."),
        ("lightgbm", "LightGBM gradient boosting framework. Use for fast ML."),
        ("llama", "Meta Llama open-source LLM family. Use for local AI."),
        ("llamaindex", "LlamaIndex data framework for LLMs. Use for RAG applications."),
        ("matplotlib", "Matplotlib data visualization library. Use for plotting."),
        ("midjourney", "Midjourney AI image generation. Use for creative AI."),
        ("mistral", "Mistral AI efficient open models. Use for efficient AI."),
        ("mlflow", "MLflow ML lifecycle management. Use for ML experiment tracking."),
        ("nltk", "NLTK natural language toolkit. Use for NLP."),
        ("numpy", "NumPy numerical computing with arrays. Use for numerical operations."),
        ("ollama", "Ollama local LLM deployment and management. Use for running LLMs locally."),
        ("openai-gpt", "OpenAI GPT models API for chat, completion, and embeddings. Use for AI integration."),
        ("opencv", "OpenCV computer vision library. Use for image processing."),
        ("pandas", "Pandas data manipulation with DataFrames. Use for data analysis."),
        ("perplexity", "Perplexity AI search and research. Use for AI search."),
        ("plotly", "Plotly interactive visualization library. Use for interactive charts."),
        ("polars", "Polars fast DataFrame library. Use for fast data processing."),
        ("pytorch", "PyTorch deep learning framework with dynamic graphs. Use for neural networks."),
        ("ray", "Ray distributed computing framework. Use for scaling ML."),
        ("scikit-learn", "Scikit-learn machine learning library. Use for classical ML."),
        ("seaborn", "Seaborn statistical data visualization. Use for statistical plots."),
        ("spacy", "spaCy NLP library with pipelines. Use for text processing."),
        ("spark", "Apache Spark distributed computing. Use for big data processing."),
        ("stable-diffusion", "Stable Diffusion image generation models. Use for image AI."),
        ("tensorflow", "TensorFlow machine learning platform with Keras. Use for ML models."),
        ("vaex", "Vaex out-of-core DataFrames. Use for big data exploration."),
        ("weights-biases", "Weights & Biases ML experiment tracking. Use for ML monitoring."),
        ("whisper", "Whisper OpenAI speech recognition. Use for speech-to-text."),
        ("xgboost", "XGBoost gradient boosting library. Use for tabular ML."),
    ],
    "architecture": [
        ("api-gateway", "API Gateway pattern for routing. Use for microservices entry."),
        ("clean-architecture", "Clean Architecture layered design. Use for maintainable code."),
        ("cqrs", "CQRS command query responsibility segregation. Use for complex domains."),
        ("domain-driven-design", "DDD tactical and strategic patterns. Use for complex domains."),
        ("event-driven", "Event-driven architecture with pub/sub and message queues. Use for reactive systems."),
        ("event-sourcing", "Event sourcing event-based persistence. Use for audit trails."),
        ("graphql", "GraphQL API query language with schema. Use for flexible APIs."),
        ("grpc", "gRPC high-performance RPC framework with protobuf. Use for service communication."),
        ("hexagonal", "Hexagonal architecture ports and adapters. Use for testable systems."),
        ("microservices", "Microservices distributed architecture pattern. Use for scalable systems."),
        ("modular-monolith", "Modular monolith with bounded contexts. Use for scalable monoliths."),
        ("monolith", "Monolithic architecture single deployment. Use for simple systems."),
        ("rest-api", "REST API design with HTTP methods and status codes. Use for web APIs."),
        ("saga", "Saga pattern for distributed transactions. Use for microservices transactions."),
        ("serverless", "Serverless architecture with FaaS and BaaS. Use for cloud functions."),
        ("service-mesh", "Service mesh for microservices networking. Use for service-to-service."),
        ("sse", "Server-Sent Events one-way real-time. Use for live updates."),
        ("twelve-factor", "Twelve-factor app methodology. Use for cloud-native apps."),
        ("webhooks", "Webhooks HTTP callbacks for events. Use for integrations."),
        ("websockets", "WebSockets real-time bidirectional communication. Use for real-time features."),
    ],
    "databases": [
        ("arangodb", "ArangoDB multi-model database with graphs. Use for multi-model workloads."),
        ("bigquery", "Google BigQuery for analytics, ML, and data warehousing. Use for large-scale analytics."),
        ("cassandra", "Apache Cassandra distributed database for high availability. Use for distributed systems."),
        ("clickhouse", "ClickHouse columnar database for analytics. Use for real-time analytics."),
        ("cockroachdb", "CockroachDB distributed SQL database. Use for geo-distributed data."),
        ("cosmosdb", "Azure Cosmos DB multi-model database with global distribution. Use for Azure."),
        ("couchbase", "Couchbase distributed NoSQL database. Use for mobile and edge."),
        ("couchdb", "CouchDB document database with sync. Use for offline-first apps."),
        ("db2", "IBM Db2 enterprise database. Use for IBM mainframe systems."),
        ("duckdb", "DuckDB analytical database for OLAP workloads. Use for embedded analytics."),
        ("dynamodb", "AWS DynamoDB serverless NoSQL with streams and global tables. Use for AWS serverless."),
        ("elasticsearch", "Elasticsearch search and analytics engine with full-text search. Use for search and logging."),
        ("firebase", "Firebase Realtime Database and Firestore for mobile/web sync. Use for real-time apps."),
        ("hbase", "Apache HBase wide-column store on Hadoop. Use for big data."),
        ("influxdb", "InfluxDB time-series database for metrics and IoT. Use for time-series data."),
        ("mariadb", "MariaDB MySQL-compatible database with Galera clustering. Use for MySQL-compatible database needs."),
        ("memcached", "Memcached distributed memory caching. Use for simple caching."),
        ("mongodb", "MongoDB document database with aggregation pipeline and Atlas. Use for document storage."),
        ("mysql", "MySQL relational database with InnoDB, replication, and stored procedures. Use for MySQL operations."),
        ("neo4j", "Neo4j graph database with Cypher query language. Use for graph-based data."),
        ("neon", "Neon serverless PostgreSQL with branching. Use for serverless Postgres."),
        ("oracle", "Oracle Database with PL/SQL, RAC, and enterprise features. Use for enterprise systems."),
        ("planetscale", "PlanetScale serverless MySQL with branching. Use for scalable MySQL."),
        ("postgresql", "PostgreSQL relational database with JSONB, CTEs, window functions, and extensions. Use for SQL queries."),
        ("redis", "Redis in-memory cache, pub/sub, streams, and data structures. Use for caching and real-time data."),
        ("snowflake", "Snowflake cloud data warehouse with data sharing. Use for cloud analytics."),
        ("sqlite", "SQLite embedded database for local storage and mobile apps. Use for lightweight database needs."),
        ("sqlserver", "Microsoft SQL Server with T-SQL, SSMS, and enterprise features. Use for Windows/Azure."),
        ("supabase", "Supabase PostgreSQL backend-as-a-service with realtime. Use for serverless PostgreSQL."),
        ("timescaledb", "TimescaleDB PostgreSQL for time-series. Use for time-series on Postgres."),
    ],
    "devops": [
        ("ansible", "Ansible configuration management with playbooks and roles. Use for server provisioning."),
        ("apache", "Apache HTTP Server web server. Use for traditional web hosting."),
        ("argocd", "ArgoCD GitOps continuous delivery for Kubernetes. Use for K8s GitOps."),
        ("aws", "Amazon Web Services cloud platform with Lambda, EC2, S3, and RDS. Use for AWS infrastructure."),
        ("awscli", "AWS CLI command-line interface. Use for AWS automation."),
        ("azure", "Microsoft Azure cloud platform with Functions, AKS, and DevOps. Use for Azure services."),
        ("azurecli", "Azure CLI command-line interface. Use for Azure automation."),
        ("caddy", "Caddy automatic HTTPS web server. Use for simple web serving."),
        ("cargo", "Cargo Rust package manager and build system. Use for Rust crates."),
        ("circleci", "CircleCI cloud CI/CD platform. Use for continuous integration."),
        ("cloudflare", "Cloudflare CDN, Workers, and edge services. Use for CDN and edge."),
        ("consul", "HashiCorp Consul service discovery and mesh. Use for service discovery."),
        ("datadog", "Datadog monitoring and APM platform. Use for observability."),
        ("digitalocean", "DigitalOcean cloud platform with droplets. Use for simple cloud."),
        ("docker", "Docker containerization with Dockerfile, Compose, and multi-stage builds. Use for containers."),
        ("fly-io", "Fly.io edge platform with global distribution. Use for edge deployment."),
        ("gcloud", "Google Cloud SDK command-line tools. Use for GCP automation."),
        ("gcp", "Google Cloud Platform with Cloud Run, GKE, and BigQuery. Use for GCP infrastructure."),
        ("github-actions", "GitHub Actions CI/CD workflows with reusable actions. Use for GitHub automation."),
        ("gitlab-ci", "GitLab CI/CD pipelines with runners and stages. Use for GitLab automation."),
        ("grafana", "Grafana dashboards and visualization for metrics. Use for observability."),
        ("haproxy", "HAProxy load balancer and proxy. Use for high-availability."),
        ("helm", "Helm Kubernetes package manager with charts. Use for K8s deployments."),
        ("heroku", "Heroku platform-as-a-service with buildpacks. Use for easy deployment."),
        ("homebrew", "Homebrew macOS/Linux package manager. Use for system tools."),
        ("istio", "Istio service mesh for Kubernetes. Use for service networking."),
        ("jenkins", "Jenkins automation server with pipelines and plugins. Use for CI/CD pipelines."),
        ("kubernetes", "Kubernetes container orchestration with Helm, operators, and service mesh. Use for cluster management."),
        ("linkerd", "Linkerd lightweight service mesh. Use for service networking."),
        ("linode", "Linode cloud computing platform. Use for Linux cloud servers."),
        ("netlify", "Netlify web deployment with serverless functions. Use for static hosting."),
        ("nginx", "Nginx web server, reverse proxy, and load balancer. Use for web serving."),
        ("nomad", "HashiCorp Nomad workload orchestration. Use for job scheduling."),
        ("npm", "npm Node.js package manager and registry. Use for JavaScript dependencies."),
        ("openshift", "OpenShift enterprise Kubernetes platform. Use for enterprise K8s."),
        ("packer", "HashiCorp Packer image building. Use for machine images."),
        ("pip", "pip Python package manager. Use for Python packages."),
        ("pnpm", "pnpm fast package manager with content-addressable storage. Use for efficient installs."),
        ("podman", "Podman daemonless container engine. Use for rootless containers."),
        ("prometheus", "Prometheus monitoring and alerting with PromQL. Use for metrics collection."),
        ("pulumi", "Pulumi infrastructure as code with programming languages. Use for IaC."),
        ("railway", "Railway platform for instant deployments. Use for simple hosting."),
        ("rancher", "Rancher Kubernetes management platform. Use for multi-cluster K8s."),
        ("render", "Render unified cloud for web services. Use for managed hosting."),
        ("sentry", "Sentry error tracking and performance monitoring. Use for error tracking."),
        ("terraform", "Terraform infrastructure as code with providers and state management. Use for cloud provisioning."),
        ("traefik", "Traefik cloud-native reverse proxy. Use for container networking."),
        ("vagrant", "Vagrant development environments with VMs. Use for dev environments."),
        ("vercel", "Vercel frontend deployment with edge functions. Use for frontend hosting."),
        ("yarn", "Yarn package manager with workspaces. Use for JavaScript dependencies."),
    ],
    "frameworks": [
        ("actix", "Actix Rust web framework with actors and high performance. Use for Rust APIs."),
        ("angular", "Angular TypeScript framework with dependency injection and RxJS. Use for enterprise SPAs."),
        ("aspnet-core", "ASP.NET Core cross-platform .NET framework with Blazor support. Use for C# web apps."),
        ("astro", "Astro static site builder with islands architecture and content collections. Use for content sites."),
        ("axum", "Axum ergonomic Rust web framework with tower. Use for Rust APIs."),
        ("blazor", "Blazor .NET WebAssembly and Server framework. Use for C# frontend."),
        ("bootstrap", "Bootstrap CSS framework for responsive design. Use for quick styling."),
        ("bun", "Bun fast JavaScript runtime and bundler. Use for fast JS development."),
        ("chakraui", "Chakra UI accessible React components. Use for React UI."),
        ("deno", "Deno secure JavaScript/TypeScript runtime. Use for modern JS backend."),
        ("django", "Django Python full-stack framework with ORM, admin, and auth. Use for Python web apps."),
        ("drizzle", "Drizzle TypeScript ORM with SQL-like syntax. Use for database access."),
        ("echo", "Echo high-performance Go web framework. Use for Go APIs."),
        ("electron", "Electron cross-platform desktop apps with web technologies. Use for desktop apps."),
        ("express", "Express.js Node.js web framework for REST APIs and middleware. Use for Node.js backends."),
        ("fastapi", "FastAPI Python async framework with Pydantic and automatic OpenAPI. Use for Python APIs."),
        ("fiber", "Fiber Express-inspired Go web framework. Use for Go APIs."),
        ("flask", "Flask Python microframework with blueprints and extensions. Use for lightweight APIs."),
        ("gatsby", "Gatsby React static site generator with GraphQL. Use for static sites."),
        ("gin", "Gin Go web framework with high performance and middleware. Use for Go APIs."),
        ("hono", "Hono ultrafast web framework for edge computing. Use for edge APIs."),
        ("htmx", "HTMX HTML-first approach with AJAX attributes. Use for server-rendered interactivity."),
        ("jquery", "jQuery DOM manipulation and AJAX for legacy projects. Use for older web projects."),
        ("laravel", "Laravel PHP framework with Eloquent ORM and Blade templates. Use for PHP applications."),
        ("materialui", "Material UI React component library. Use for React UI."),
        ("nestjs", "NestJS TypeScript backend framework with decorators and modules. Use for Node.js APIs."),
        ("nextjs", "Next.js React framework with SSR, App Router, and server components. Use for full-stack React."),
        ("nodejs", "Node.js server-side JavaScript runtime with npm ecosystem. Use for backend development."),
        ("nuxt", "Nuxt.js Vue framework with SSR and auto-imports. Use for full-stack Vue applications."),
        ("phoenix", "Phoenix Elixir framework with LiveView for real-time. Use for Elixir apps."),
        ("prisma", "Prisma TypeScript ORM with migrations. Use for database access."),
        ("rails", "Ruby on Rails MVC framework with Active Record and conventions. Use for rapid development."),
        ("react", "React component-based UI with hooks, context, and state management. Use for .jsx/.tsx files."),
        ("remix", "Remix React framework with nested routing and data loading. Use for full-stack React."),
        ("sanity", "Sanity structured content platform. Use for content management."),
        ("shadcnui", "shadcn/ui copy-paste React components. Use for modern React UI."),
        ("solidjs", "SolidJS reactive UI library with fine-grained reactivity and JSX. Use for performant React-like apps."),
        ("spring-boot", "Spring Boot Java framework for microservices with auto-configuration. Use for enterprise Java."),
        ("strapi", "Strapi headless CMS with REST and GraphQL. Use for content APIs."),
        ("svelte", "Svelte compile-time framework with reactive declarations. Use for .svelte files."),
        ("sveltekit", "SvelteKit full-stack Svelte framework with SSR and routing. Use for Svelte applications."),
        ("symfony", "Symfony PHP framework with reusable components. Use for PHP applications."),
        ("tailwindcss", "Tailwind CSS utility-first framework. Use for custom designs."),
        ("tauri", "Tauri lightweight desktop framework with Rust backend. Use for desktop apps."),
        ("vue", "Vue.js progressive framework with Composition API and Pinia. Use for .vue files."),
        ("vuetify", "Vuetify Material Design component framework for Vue. Use for Vue UI."),
        ("wordpress", "WordPress CMS development with themes, plugins, and Gutenberg. Use for content sites."),
    ],
    "languages": [
        ("assembly", "Assembly language for low-level system and embedded programming. Use for .asm files."),
        ("bash", "Bash shell scripting for automation, pipelines, and system administration. Use for .sh files and Linux scripting."),
        ("c", "C programming with memory management, pointers, structs, and system-level development. Use for .c files."),
        ("clojure", "Clojure functional programming on the JVM with immutable data. Use for .clj files."),
        ("cobol", "COBOL for mainframe and legacy business systems. Use for .cob files."),
        ("cpp", "C++ modern C++17/20/23 with STL, smart pointers, and performance optimization. Use for .cpp files."),
        ("crystal", "Crystal Ruby-like syntax with static typing. Use for .cr files."),
        ("csharp", "C# programming for .NET, ASP.NET Core, LINQ, async patterns, and Entity Framework. Use for .cs files."),
        ("dart", "Dart programming for Flutter mobile and web development. Use for .dart files."),
        ("delphi", "Delphi Object Pascal for Windows applications. Use for .pas files."),
        ("elixir", "Elixir functional programming with OTP, GenServer, and Phoenix. Use for .ex files."),
        ("erlang", "Erlang concurrent programming with OTP. Use for .erl files."),
        ("fortran", "Fortran for scientific and numerical computing. Use for .f90 files."),
        ("fsharp", "F# functional-first programming on .NET. Use for .fs files."),
        ("go", "Go (Golang) with goroutines, channels, interfaces, and idiomatic patterns. Use for .go files."),
        ("groovy", "Groovy scripting for JVM, Gradle builds, and Jenkins pipelines. Use for .groovy files."),
        ("haskell", "Haskell pure functional programming with monads and type classes. Use for .hs files."),
        ("html-css", "HTML5 and CSS3 for web structure, styling, flexbox, grid, and responsive layouts. Use for .html and .css files."),
        ("java", "Java OOP with Spring ecosystem, Maven/Gradle, streams, and JVM optimization. Use for .java files."),
        ("javascript", "JavaScript ES6+ programming including async/await, DOM manipulation, modules, and Node.js. Use for .js files and web development."),
        ("julia", "Julia scientific computing for numerical analysis and data science. Use for .jl files."),
        ("kotlin", "Kotlin programming for Android, coroutines, and JVM development. Use for .kt files."),
        ("lua", "Lua scripting for game development, embedded systems, and configuration. Use for .lua files."),
        ("nim", "Nim systems programming with Python-like syntax. Use for .nim files."),
        ("objective-c", "Objective-C for legacy iOS/macOS development with manual memory. Use for .m files."),
        ("ocaml", "OCaml functional programming with type inference. Use for .ml files."),
        ("perl", "Perl text processing and scripting with regular expressions. Use for .pl files."),
        ("php", "PHP 8+ web development with Composer, attributes, and modern frameworks. Use for .php files."),
        ("powershell", "PowerShell scripting for Windows automation, cmdlets, and administration. Use for .ps1 files."),
        ("python", "Python programming with type hints, async/await, decorators, and package management. Use for .py files and data science."),
        ("r", "R statistical programming for data analysis, visualization, and modeling. Use for .r files."),
        ("ruby", "Ruby programming with blocks, metaprogramming, gems, and Rails conventions. Use for .rb files."),
        ("rust", "Rust programming with ownership, borrowing, lifetimes, and zero-cost abstractions. Use for .rs files."),
        ("scala", "Scala functional and OOP programming on the JVM with Akka. Use for .scala files."),
        ("solidity", "Solidity smart contract development for Ethereum and EVM chains. Use for .sol files."),
        ("sql", "SQL database queries, joins, aggregations, subqueries, and optimization. Use for .sql files and database operations."),
        ("swift", "Swift development for iOS/macOS with SwiftUI, async/await, and Combine. Use for .swift files."),
        ("typescript", "TypeScript static typing with interfaces, generics, decorators, and type inference. Use for .ts files."),
        ("v", "V simple systems programming language. Use for .v files."),
        ("vbnet", "Visual Basic .NET for legacy .NET applications. Use for .vb files."),
        ("zig", "Zig systems programming with manual memory and no hidden control flow. Use for .zig files."),
    ],
    "mobile": [
        ("android-sdk", "Android SDK development tools. Use for native Android."),
        ("capacitor", "Capacitor cross-platform native runtime. Use for web to native."),
        ("cordova", "Apache Cordova hybrid mobile framework. Use for hybrid apps."),
        ("expo", "Expo React Native development platform. Use for React Native apps."),
        ("flutter", "Flutter cross-platform UI toolkit with Dart. Use for mobile/web/desktop."),
        ("ionic", "Ionic hybrid mobile framework with web technologies. Use for hybrid mobile apps."),
        ("jetpack-compose", "Jetpack Compose Android declarative UI. Use for Android."),
        ("kotlin-multiplatform", "Kotlin Multiplatform for shared code. Use for cross-platform."),
        ("nativescript", "NativeScript native mobile with JS. Use for native mobile."),
        ("react-native", "React Native cross-platform mobile with JavaScript. Use for iOS/Android."),
        ("swiftui", "SwiftUI declarative Apple UI framework. Use for iOS/macOS."),
        ("uikit", "UIKit imperative iOS UI framework. Use for iOS development."),
        ("xamarin", "Xamarin cross-platform with .NET. Use for .NET mobile."),
    ],
    "security": [
        ("auth0", "Auth0 identity platform. Use for authentication."),
        ("bcrypt", "bcrypt password hashing. Use for password security."),
        ("burpsuite", "Burp Suite web security testing. Use for penetration testing."),
        ("certbot", "Certbot Let's Encrypt certificates. Use for SSL/TLS."),
        ("clerk", "Clerk authentication for modern apps. Use for user management."),
        ("dependabot", "Dependabot dependency updates. Use for security updates."),
        ("jwt", "JSON Web Tokens for secure transmission. Use for authentication."),
        ("keycloak", "Keycloak identity and access management. Use for SSO."),
        ("nextauth", "NextAuth.js authentication for Next.js. Use for Next.js auth."),
        ("oauth", "OAuth 2.0 authorization framework. Use for authorization."),
        ("okta", "Okta identity management. Use for enterprise SSO."),
        ("openid-connect", "OpenID Connect identity layer. Use for SSO."),
        ("owasp-zap", "OWASP ZAP security testing proxy. Use for security testing."),
        ("passport", "Passport.js authentication middleware. Use for Node.js auth."),
        ("renovate", "Renovate dependency updates. Use for automated updates."),
        ("snyk", "Snyk security scanning for dependencies. Use for vulnerability scanning."),
        ("sonarqube", "SonarQube code quality and security. Use for code analysis."),
        ("trivy", "Trivy container security scanner. Use for container security."),
        ("vault", "HashiCorp Vault secrets management. Use for secrets."),
    ],
    "testing": [
        ("appium", "Appium mobile app automation. Use for mobile testing."),
        ("cargo-test", "Cargo test for Rust testing. Use for Rust testing."),
        ("chai", "Chai assertion library for JavaScript. Use for JS assertions."),
        ("cypress", "Cypress end-to-end testing for web apps. Use for E2E testing."),
        ("detox", "Detox React Native E2E testing. Use for RN testing."),
        ("gatling", "Gatling load testing for APIs. Use for load testing."),
        ("go-test", "Go testing package. Use for Go testing."),
        ("jest", "Jest JavaScript testing framework with snapshots. Use for JS testing."),
        ("junit", "JUnit Java testing framework. Use for Java testing."),
        ("k6", "k6 load testing tool. Use for performance testing."),
        ("locust", "Locust load testing in Python. Use for load testing."),
        ("mocha", "Mocha JavaScript test framework. Use for Node.js testing."),
        ("nunit", "NUnit .NET testing framework. Use for .NET testing."),
        ("phpunit", "PHPUnit PHP testing framework. Use for PHP testing."),
        ("playwright", "Playwright end-to-end testing for web. Use for browser automation."),
        ("puppeteer", "Puppeteer headless Chrome automation. Use for browser automation."),
        ("pytest", "pytest Python testing framework with fixtures. Use for Python testing."),
        ("rspec", "RSpec Ruby testing framework. Use for Ruby testing."),
        ("selenium", "Selenium browser automation framework. Use for web testing."),
        ("storybook", "Storybook UI component development and testing. Use for component testing."),
        ("testing-library", "Testing Library user-centric testing. Use for React testing."),
        ("testng", "TestNG Java testing framework. Use for Java testing."),
        ("vitest", "Vitest fast Vite-native testing. Use for Vite projects."),
        ("webdriver", "WebDriver browser automation protocol. Use for cross-browser testing."),
        ("xunit", "xUnit .NET testing framework. Use for .NET testing."),
    ],
    "tools": [
        ("android-studio", "Android Studio IDE with emulator and profiler. Use for Android development."),
        ("atom", "Atom hackable text editor from GitHub. Use for extensible editing."),
        ("babel", "Babel JavaScript compiler for compatibility. Use for transpiling."),
        ("biome", "Biome fast formatter and linter. Use for code quality."),
        ("bitbucket", "Bitbucket Git repository hosting with Pipelines. Use for Atlassian teams."),
        ("confluence", "Confluence team documentation platform. Use for documentation."),
        ("cursor", "Cursor AI-powered code editor with chat. Use for AI-assisted coding."),
        ("datagrip", "DataGrip database IDE from JetBrains. Use for database management."),
        ("dbeaver", "DBeaver universal database tool. Use for database management."),
        ("discord", "Discord community communication platform. Use for community chat."),
        ("docker-desktop", "Docker Desktop for Mac/Windows. Use for local containers."),
        ("eclipse", "Eclipse Java IDE with plugins. Use for Java development."),
        ("emacs", "Emacs extensible text editor with Lisp. Use for terminal editing."),
        ("esbuild", "esbuild extremely fast bundler. Use for fast builds."),
        ("eslint", "ESLint JavaScript linter with plugins. Use for code quality."),
        ("figma", "Figma collaborative design tool. Use for UI/UX design."),
        ("fish", "Fish friendly interactive shell. Use for terminal shell."),
        ("git", "Git version control with branching, merging, and rebasing. Use for source control."),
        ("github", "GitHub platform with Actions, Copilot, and code review. Use for collaboration."),
        ("gitlab", "GitLab DevOps platform with CI/CD and security. Use for DevOps."),
        ("goland", "GoLand Go IDE with debugging and testing. Use for Go development."),
        ("httpie", "HTTPie human-friendly HTTP client. Use for API testing."),
        ("insomnia", "Insomnia API client for REST and GraphQL. Use for API testing."),
        ("intellij", "IntelliJ IDEA JetBrains IDE with smart completion. Use for JVM development."),
        ("iterm2", "iTerm2 macOS terminal emulator. Use for terminal work."),
        ("jira", "Jira project management and issue tracking. Use for agile teams."),
        ("k9s", "k9s terminal UI for Kubernetes. Use for K8s management."),
        ("lazygit", "lazygit terminal UI for git. Use for git operations."),
        ("lens", "Lens Kubernetes IDE. Use for K8s management."),
        ("linear", "Linear issue tracking for modern teams. Use for project management."),
        ("neovim", "Neovim modern Vim fork with Lua plugins and LSP. Use for extensible terminal editing."),
        ("notepad-plus-plus", "Notepad++ text editor for Windows. Use for quick editing."),
        ("notion", "Notion workspace for docs and collaboration. Use for documentation."),
        ("obsidian", "Obsidian knowledge management with markdown. Use for note-taking."),
        ("parcel", "Parcel zero-config bundler. Use for simple bundling."),
        ("phpstorm", "PhpStorm PHP IDE with debugging. Use for PHP development."),
        ("postman", "Postman API platform for testing and documentation. Use for API testing."),
        ("prettier", "Prettier code formatter for consistent style. Use for formatting."),
        ("pycharm", "PyCharm Python IDE with debugging and testing. Use for Python development."),
        ("rider", "JetBrains Rider .NET IDE with ReSharper. Use for .NET development."),
        ("rollup", "Rollup ES module bundler. Use for library bundling."),
        ("rubymine", "RubyMine Ruby IDE with Rails support. Use for Ruby development."),
        ("sketch", "Sketch macOS design tool. Use for UI design."),
        ("slack", "Slack team communication platform. Use for team chat."),
        ("sublime-text", "Sublime Text fast editor with multiple cursors. Use for quick editing."),
        ("swc", "SWC Rust-based JS/TS compiler. Use for fast compilation."),
        ("tableplus", "TablePlus modern database GUI. Use for database management."),
        ("tig", "tig text-mode git interface. Use for git browsing."),
        ("tmux", "tmux terminal multiplexer. Use for terminal sessions."),
        ("turbopack", "Turbopack Rust-powered bundler. Use for fast builds."),
        ("vim", "Vim text editor with motions, macros, and plugins. Use for terminal editing."),
        ("visual-studio", "Visual Studio IDE for Windows with debugging and profiling. Use for .NET development."),
        ("vite", "Vite fast build tool with HMR. Use for modern frontend builds."),
        ("vscode", "Visual Studio Code editor with extensions and debugging. Use for code editing."),
        ("warp", "Warp modern terminal with AI. Use for terminal work."),
        ("webpack", "Webpack module bundler with loaders and plugins. Use for bundling."),
        ("webstorm", "WebStorm JavaScript IDE with debugging. Use for web development."),
        ("xcode", "Xcode Apple development IDE with simulators. Use for iOS/macOS development."),
        ("zed", "Zed high-performance collaborative editor. Use for fast editing."),
        ("zsh", "Zsh shell with oh-my-zsh. Use for terminal shell."),
    ],
}


def generate_content(name: str, description: str) -> str:
    content = load_template()
    title = name.replace("-", " ").title()
    content = content.replace("name: template", f"name: {name}")
    content = content.replace("description: Expert [skill-name] assistance covering [feature 1], [feature 2], and [feature 3]. Use when [working with X], [debugging Y], or [implementing Z].", f"description: {description}")
    content = content.replace("# Skill Name", f"# {title}")
    return content


def create_skill(category: str, name: str, description: str) -> bool:
    skill_dir = SKILLS_PATH / category / name
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_file = skill_dir / "SKILL.md"
    if skill_file.exists():
        return False
    skill_file.write_text(generate_content(name, description))
    print(f"Created: {category}/{name}")
    return True


def main() -> int:
    stats = {cat: {"created": 0, "skipped": 0} for cat in SKILLS}

    for category, skills in SKILLS.items():
        for name, description in skills:
            if create_skill(category, name, description):
                stats[category]["created"] += 1
            else:
                stats[category]["skipped"] += 1

    print(f"{'Category':<20} {'Created':>8} {'Skipped':>8} {'Total':>8}")
    print("-" * 48)
    total_created = total_skipped = 0
    for cat, counts in stats.items():
        created, skipped = counts["created"], counts["skipped"]
        total_created += created
        total_skipped += skipped
        print(f"{cat:<20} {created:>8} {skipped:>8} {created + skipped:>8}")
    print("-" * 48)
    print(f"{'Total':<20} {total_created:>8} {total_skipped:>8} {total_created + total_skipped:>8}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
